### PR TITLE
feat: Create Statefulset for containers that consume storage

### PR DESCRIPTION
**Pull request by mhutter**
- [x] If a service produces any volumes, use a StatefulSet instead of a Deployment
- [x] Create Volume Template instead of PVC
- [x] Allow changing this behavior via a Label on the Compose service
- [x] note about PVC templates
- [x] use `IsTruthy` where it makes sense

### CODE REVIEW

**Comment by davidgubler** [comment]
The isTruthy() function should be used for checking the "k8ify.singleton" label as well.

**Comment by davidgubler** [comment]
That's all I have for now.

**Comment by mhutter** [comment]
> There is a bug: The persistentVolumeClaims are not created for StatefulSets.

It's a feature, actually. StatefulSets have a field `volumeTemplate`, which is used to dynamically create PVC's for each replica.

**Comment by davidgubler** [comment]
> StatefulSets have a field volumeTemplate

Ah, I see! Can you perhaps add a short comment about this in the code? Thanks!

**Comment by mhutter** [comment]
@davidgubler PR is ready, feel free to merge

**Comment by davidgubler** [comment]
LGTM, thank you!

**Pull request merged**
