### PR TITLE
Refactor Volume management

### PR DESCRIPTION
**Pull request by mhutter**
Closes: APPX-23

- [x] Update Documentation
- [x] Add some golden test cases
- [x] Remove `k8ify.share-storage` from services -- it's obsolete

### CODE REVIEW

**Comment by mhutter** [comment]
@davidgubler I think this is ready now

**Comment by davidgubler** [comment]
* If no storage size is defined then there must at least be a warning (IMHO this is pretty important)
* At the moment the RAM is parsed base 1024 even if the unit is 'M' (as far as I can tell using this parser: https://github.com/docker/go-units/blob/master/size.go#L86 ) and the storage is parsed using the K8s parser. I would prefer to have consistency here and use the parser from go-units everywhere (since the parser for the memory reservations is given by the compose spec the only option to have consistency is to use the compose parser everywhere). If you really don't want to do that I can live with the current version too though (worst case the user will end up allocating RAM base 1024 and storage base 1000, which is a bit weird but not catastrophic).
* Use default size 1Gi instead of 100Mi or error instead of using a default (no hard feelings on this one)

Apart from that my superficial tests seem to produce reasonable results and I see no more conceptual issues :+1:

**Comment by mhutter** [comment]
@davidgubler I'm not sure about the storage parsing one. Personally I would always assume for RAM sizes to be in binary notation (base 1024), but Disk sizes to be in decimal notation (base 1000).

I have implemented your proposal, but it produces weird results (the K8s library will always render storage sizes in decimal units)

https://github.com/vshn/k8ify/pull/30/files#diff-3074fba2c106f03d863c89eef44a03d3e928c9c854f1fd00793db69d85dce6b8L71-R67

**Comment by davidgubler** [comment]
LGTM now, thanks!

**Pull request merged**
