### PR TITLE
feat: Add support for CPU and memory requests/limits

### PR DESCRIPTION
**Pull request by davidgubler**

### CODE REVIEW

**Comment by davidgubler** [comment]
@mhutter what do you think about the defaults?

I was also considering not setting any requests and limits if there aren't any in docker-compose, which would make sense in a puristic sense. However that likely causes problems down the road so I think we should enforce requests and limits.

**Comment by mhutter** [comment]
I am torn to all sides:

* setting requests is a best practice, however
* resource requirements are highly specific to the application. Some Java Spring applications will not start with less than 1 GB, but some Go services might only need a couple of MB during their lifetime.
* on the other hand, not setting them explicitly may lead to bad experience on APPUiO Cloud, as there the cluster will apply default values if none are set
* … which also means that for APPUiO Cloud, the requests have a cost implication.
* I think it's necessary that it's possible to remove CPU limits altogether (IIRC [this is still not properly fixed](https://medium.com/omio-engineering/cpu-limits-and-aggressive-throttling-in-kubernetes-c5b20bd8a718))

For reference, the defaults applied on APPUiO Cloud are:

```
Type        Resource           Min    Max  Default Request  Default Limit  Max Limit/Request Ratio
----        --------           ---    ---  ---------------  -------------  -----------------------
Container   memory             4Mi    -    100Mi            768Mi          -
Container   cpu                10m    -    10m              600m           -
Container   ephemeral-storage  100Ki  -    100Ki            -              -
```

**Comment by davidgubler** [comment]
An option would be for k8ify to fail (or at least warn) if it can't find any limits. I think this would be the best approach if we can't give any sensible defaults.

**Comment by mhutter** [comment]
Good point, at least some kind of Warning should be emitted

**Comment by davidgubler** [comment]
OK so requirements are:
* It *must* be possible to set requests but not limits (it doesn't need to be easy or the default, but it must be possible)
* The user *must* be pressured into setting requests and limits
* k8ify *should* work even if no limits or no requests are set (I don't like it when tools fail just because I did one of 100 things wrong, this makes the "getting started" curve steep because I need to get everything right to get any result at all). This could mean not setting requests/limits at all or setting some defaults.
* It *should* be enough to set requests but not limits (try to make the developer's life easier in case he doesn't entirely understand what they do. Probably use the existing factor 10 for CPU and 1 for memory)


I'll think about how to implement this tomorrow.

**Comment by davidgubler** [comment]
OK now:
* If you don't set `deploy.resources.reservations` you get a big fat red warning message, but k8ify will continue WITHOUT requests/limits (hence the platform defaults will apply, if any)
* If you set reservations, the limits will be set automatically as well
* You can set reservations and set the limits explicitly, in which case nothing will be set automatically (e.g. you can set request for CPU but not set limits for CPU)

I think this covers everything and the magic is very limited (only magic is to set limits if there are only requests). Also we do not have to maintain any arbitrary default values.

**Review by mhutter — APPROVED** [review]

**Pull request merged**
