### PR TITLE
feat: Allow configuration of Replicas

### PR DESCRIPTION
**Pull request by mhutter**

### CODE REVIEW

**Comment by mhutter** [comment]
@davidgubler an Idea I just had: Ommit replicas entirely if it's not defined in the compose file. This would leave whatever is already configured on the cluster, eg. for manually scaled deployments

**Comment by davidgubler** [comment]
> Omit replicas entirely if it's not defined in the compose file. 

I am not entirely sure if that works but if it does work I it certainly sounds like a good solution.

**Comment by mhutter** [comment]
I did a few tests to determine the behavior, and it's, uh, "interesting". Now for context, it's important to know that `kubectl apply` will, for each resource created, save a JSON-serialized version of whatever you wrote in the input file into an annotation  `kubectl.kubernetes.io/last-applied-configuration`. This annotation is updated each time `kubectl apply` is re-run.

---

If `spec.replicas` is set in the YAML file, `kubectl apply` will overwrite whatever is configured on the cluster. (so far so good)

If `spec.replicas` is unset, and the version in the "last-applied-configuration" did also NOT contain a value, `kubectl apply` will leave whatever is set on the cluster.

If `spec.replicas` is unset, but the version in the "last-applied-configuration" DID contain a value, `kubectl apply` will overwrite whatever is set on the cluster with what was saved to "last-applied-configuration". (Subsequent `kubectl apply` runs will then ignore the replicas since now there is no value set in "last-applied-configuration" anymore.)

---

I think switching between having replicas configured explicitly and not is an edge case. I'll therefore update the PR, I think this causes the least surprises.

**Comment by davidgubler** [comment]
LGTM, given the behavior of kubectl I agree that this variant seems reasonable. Feel free to merge.

**Pull request merged**
