### PR TITLE
feat: Add support for Service type "LoadBalancer"

### PR DESCRIPTION
**Pull request by davidgubler**
See internal ticket APPX-104

### CODE REVIEW

**Comment by martini-source** [comment]
This does not yet seem to work correctly for multiple k8s services from a single compose service.
There does not seem to be a way, in the line of "k8ify.expose.$Port", to choose which of the service ports should be a LoadBalancer type service.
I've added a testcase to illustrate it.

**Comment by davidgubler** [comment]
@martini-source  How about now? 

It now creates a separate service resource for each combination of settings, and the name of the service resource includes the port number(s) (except for the default settings where the port number(s) are not included in order to keep things neat and backwards compatible).

**Comment by davidgubler** [comment]
@martini-source  is currently reviewing this but it may make sense for you @mhutter to have a quick look at this as well to see if it makes sense on a more conceptual level.

**Review by martini-source — APPROVED** [review]
LGTM, thank you !

**Review by mhutter — APPROVED** [review]
LGTM :+1:

**Comment by davidgubler** [comment]
Thanks for the reviews!

**Pull request merged**
