### PR TITLE
add: Test for empty env vars

### PR DESCRIPTION
**Pull request by davidgubler**
See internal ticket APPX-85

### CODE REVIEW

**Comment by martini-source** [comment]
@davidgubler I've explained in more detail in the internal ticket.
Tl;dr - With the above commit I have added a guard to the prechecks the displays an error and quits if there are nil values in the environment variables, to keep the program from panicking due to user input.

**Comment by davidgubler** [comment]
@martini-source Thanks for the feedback! The current pull request does the following:

* Add a warning for environment variables that are null
* Handles environment variables that are null gracefully (treats them as empty string)
* Fixes some consistency issues in the pre-check errors/warnings
* Adds a test for various variants of empty environment variables using the list syntax in the compose file
* Same for the map syntax

WDYT?

**Review by martini-source — APPROVED** [review]
LGTM, thank you !

**Comment by davidgubler** [comment]
@martini-source  Thanks for the review!

**Pull request merged**
